name: BAIDU

on:
  schedule:
    - cron: "3 23 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: baidu
      env:
#        TOK: ${{secrets.TOK}}
#        TOK1: ${{secrets.TOK1}}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python baidu.py
